# Generated by Django 4.1.5 on 2023-02-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0002_remove_client_fullname_client_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='status',
            field=models.CharField(choices=[('0', 'Cancelled order'), ('1', 'Placed Order'), ('2', 'Shipped Order'), ('3', 'Delivered Order')], max_length=1),
        ),
    ]
