# Generated by Django 4.1.5 on 2023-02-06 22:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0004_description_orderitems_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='created_at',
        ),
        migrations.AddField(
            model_name='description',
            name='when_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 2, 6, 17, 22, 4, 332987)),
        ),
    ]
