# Generated by Django 4.1.5 on 2023-03-07 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0005_remove_description_created_at_description_when_added'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name_plural': 'Client'},
        ),
        migrations.AddField(
            model_name='item',
            name='interested',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='description',
            name='when_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 7, 13, 16, 55, 58926)),
        ),
    ]
