# Generated by Django 4.1.5 on 2023-03-14 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0007_alter_description_when_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='when_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 14, 14, 1, 53, 910831)),
        ),
        migrations.AlterField(
            model_name='orderitems',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
