# Generated by Django 4.1.5 on 2024-07-03 01:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0008_alter_description_when_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='description',
            name='when_added',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 7, 2, 21, 54, 24, 641213)),
        ),
    ]
